[Workspace]
Home=..\
AppSrcPath=.\AppSrc
AppHTMLPath=.\AppHtml
BitmapPath=.\Bitmaps
IdeSrcPath=.\IdeSrc
DataPath=.\Data
DDSrcPath=.\DDSrc
HelpPath=.\Help
ProgramPath=.\Programs
FileList=.\Data\FileList.cfg
Description=Base_BI_MySql_v2
